In [2]:
import numpy as np
v=np.zeros(12)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
v[5]=1
v

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [5]:
# creat a vector with values ranging from 10 to 100
v= np.arange(10,100)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [ ]:
#2D array
v=np.arange(10,19).reshape(3,3)

v

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
#to generate identity method 
v = np.eye(3)
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Creating a random matrix in 3x3x3
v= np.random.random((3,3,3))
v

array([[[0.97140634, 0.54041175, 0.79895253],
        [0.13312235, 0.84149244, 0.13801008],
        [0.91923851, 0.49158202, 0.3913995 ]]])

In [24]:
#to creat a 5x5 array with random values
v= np.random.random((5,5))
dmix,dmax=v.min(),v.max()
print(dmix,dmax)


0.09779596275229085 0.968626531343314
